EQMacEmu_Accounts/urls.py
from django.contrib import admin
from django.urls import include, path

admin.site.site_header = "EQ Archives Administration"

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path("polls/", include("polls.urls")),
    path("accounts/", include("accounts.urls")),
    path('admin/', admin.site.urls)
]

EQMacEmu_Players/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from quests.views import NPCLookupView
from django.http import HttpResponse

admin.site.site_header = "EQMacEmu Accounts Administration"

def robots_txt(request):
    lines = [
        "User-agent: *",
        "Allow: /",
        # Add any directories you want to disallow:
        # "Disallow: /admin/",
        # "Disallow: /api/",
    ]
    return HttpResponse("\n".join(lines), content_type="text/plain")

urlpatterns = [
    path(r"", lambda request: redirect("/accounts/")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("accounts/", include("accounts.urls")),
    path(settings.ADMIN_URL, admin.site.urls),  # Use the custom admin URL
    path('npc-lookup/', NPCLookupView.as_view(), name='npc_lookup'),
    path("characters/", include("characters.urls")),
    path("character_transfer/", include("character_transfer.urls")),
    path("common/", include("common.urls")),
    path("factions/", include("factions.urls")),
    path("items/", include("items.urls")),
    path("magelo/", include("magelo.urls")),
    path("npcs/", include("npcs.urls")),
    path("patch/", include("patch.urls")),
    path("pets/", include("pets.urls")),
    path("quests/", include("quests.urls")),
    path("recipes/", include("recipes.urls")),
    path("spells/", include("spells.urls")),
    path("zones/", include("zones.urls")),
    path("mdeditor/", include('mdeditor.urls')),
    path('robots.txt', robots_txt),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += staticfiles_urlpatterns()

items/urls.py
from django.urls import path

from . import views

app_name = "items"
urlpatterns = [
    path("search", views.search, name="search"),
    path("discovered", views.discovered_items, name="discovered"),
    path("view/<int:item_id>", views.view_item, name="view"),
    path("bis", views.best_in_slot, name="bis"),
    path("bis/<int:class_id>", views.best_in_slot, name="bis"),
    path('api/<int:item_id>/', views.item_detail_api, name='item_detail_api'),
]

npcs/urls.py
from django.urls import path

from . import views

app_name = "npcs"
urlpatterns = [
    path("", views.index_request, name="index"),
    path("search", views.search, name="search"),
    path("view/<int:npc_id>", views.view_npc, name="view"),
    path("api/special-ability/<str:ability_name>", views.npc_special_abilities_api, name="npc_special_ability_api"),
]

quests/urls.py
from django.urls import path

from . import views

app_name = "quests"
urlpatterns = [
    path("view/<int:quest_id>", views.view_quest, name="view"),
]

items/views.py
import logging
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db import connections
from django.views.decorators.http import require_http_methods
from django.http import Http404

from items.utils import get_class_bitmask
from items.utils import get_race_bitmask
from items.utils import build_stat_query
from items.utils import get_item_effect
from common.constants import PLAYER_CLASSES
from common.constants import PLAYER_RACES
from common.constants import EQUIPMENT_SLOTS
from common.constants import ITEM_TYPES
from common.constants import ITEM_STATS
from common.constants import CONTAINER_TYPES
from common.models.items import DiscoveredItems
from common.models.items import Items
from quests.models import Quests
from collections import namedtuple

logger = logging.getLogger(__name__)

def search(request):
    """
    Search for an item by name at url https://url.tld/items/search

    :param request: Http request
    :return: Http response
    """
    if request.method == "GET":
        return render(request=request,
                      context={
                          "IS_SEARCH": True,
                          "EQUIPMENT_SLOTS": EQUIPMENT_SLOTS,
                          "PLAYER_CLASSES": PLAYER_CLASSES,
                          "PLAYER_RACES": PLAYER_RACES,
                          "ITEM_TYPES": ITEM_TYPES,
                          "CONTAINER_TYPES": CONTAINER_TYPES,
                          "ITEM_STATS": ITEM_STATS,
                      },
                      template_name="items/search_item.html")

    if request.method == "POST":
        item_name = request.POST.get("item_name")
        item_slot = request.POST.get("item_slot", "0")
        item_type = request.POST.get("item_type", "-1")
        resists_type = request.POST.get("resists_type", "Resist")
        resists_operator = request.POST.get("resists_operator", ">")
        resists_value = request.POST.get("resists_value", "0")
        stat1 = request.POST.get("stat1", "stat1")
        stat1_operator = request.POST.get("stat1_operator", ">")
        stat1_value = request.POST.get("stat1_value", "0")
        stat2 = request.POST.get("stat2", "stat2")
        stat2_operator = request.POST.get("stat2_operator", ">")
        stat2_value = request.POST.get("stat2_value", "0")
        item_effect = request.POST.get("item_effect")
        item_has_proc = request.POST.get("item_has_proc")
        item_has_click = request.POST.get("item_has_click")
        item_has_focus = request.POST.get("item_has_focus")
        item_has_worn = request.POST.get("item_has_worn")
        player_class = request.POST.get("player_class", "0")
        player_race = request.POST.get("player_race", "0")
        container_select = request.POST.get("container_select", "Container")
        container_slots = request.POST.get("container_slots", "0")
        container_wr = request.POST.get("container_wr", "0")
        query_limit = request.POST.get("query_limit", "50")

        params_list = []
        clause = ""

        # Begin building query
        query = "SELECT * FROM items"
        if item_effect:
            clause = "AND" if clause == "WHERE" or clause == "AND" else "WHERE"
            query += """ LEFT JOIN spells_new AS proc_s ON proceffect = proc_s.id
                                        LEFT JOIN spells_new AS worn_s ON worneffect = worn_s.id
                                        LEFT JOIN spells_new AS focus_s ON focuseffect = focus_s.id
                                        LEFT JOIN spells_new AS click_s ON clickeffect = click_s.id
                                        WHERE (proc_s.name LIKE %s
                                            OR worn_s.name LIKE %s
                                            OR focus_s.name LIKE %s
                                            OR click_s.name LIKE %s)"""
            params_list.append(item_effect)
            params_list.append(item_effect)
            params_list.append(item_effect)
            params_list.append(item_effect)

        if item_name:
            clause = "AND" if clause == "WHERE" or clause == "AND" else "WHERE"
            query += f" {clause} (LOWER(items.Name) LIKE %s)"
            params_list.append(f"%{item_name.lower()}%")

        try:
            player_class = int(player_class)
        except ValueError:
            messages.error(request, "Invalid player class.  Valid options are between 1 and 15.")
            return redirect("/items/search")
        if player_class != 0:  # zero means "any" class so no need to filter
            clause = "AND" if clause == "WHERE" or clause == "AND" else "WHERE"
            query += f" {clause} (((classes & %s) = %s) OR (classes = '32767'))"
            player_class = get_class_bitmask(player_class)
            # yes, twice - there are two parameters above
            params_list.append(player_class)
            params_list.append(player_class)

        try:
            player_race = int(player_race)
        except ValueError:
            messages.error(request, "Invalid player race.")
            return redirect("/items/search")
        if player_race != 0:  # zero means "any" race so no need to filter
            clause = "AND" if clause == "WHERE" or clause == "AND" else "WHERE"
            query += f" {clause} (((races & %s) = %s) OR (races = '16384'))"
            player_race = get_race_bitmask(player_race)
            # yes, twice - there are two parameters above
            params_list.append(player_race)
            params_list.append(player_race)

        try:
            item_slot = int(item_slot)
        except ValueError:
            messages.error(request, "Invalid item slot.")
            return redirect("/items/search")
        if item_slot != 0:  # zero means "any" slot so no need to filter
            clause = "AND" if clause == "WHERE" or clause == "AND" else "WHERE"
            query += f" {clause} ((slots & %s) = %s)"
            # yes, twice - there are two parameters above
            params_list.append(item_slot)
            params_list.append(item_slot)

        try:
            item_type = int(item_type)
        except ValueError:
            messages.error(request, "Invalid item type.")
            return redirect("/items/search")
        if item_type != -1:
            clause = "AND" if clause == "WHERE" or clause == "AND" else "WHERE"
            query += f" {clause} itemtype = %s"
            params_list.append(item_type)

        try:
            resists_value = int(resists_value)
        except ValueError:
            messages.error(request, "Invalid resist value. Must be an integer.")
            return redirect("/items/search")

        if resists_type != 'Resist':  # if no resist type was set, no need to filter
            allowed_resist_types = {'mr': 'mr', 'fr': 'fr', 'cr': 'cr', 'dr': 'dr', 'pr': 'pr'}
            if resists_type not in allowed_resist_types.keys():
                messages.error(request, "Invalid resist type.")
                return redirect("/items/search")
            else:
                resists_type = allowed_resist_types[resists_type]  # just an extra precaution
            allowed_resists_operators = {'>': '>', '>=': '>=', '=': '=', '<=': '<=', '<': '<'}
            if resists_operator not in allowed_resists_operators.keys():
                messages.error(request, "Invalid resist operator.")
                return redirect("/items/search")
            else:
                resists_operator = allowed_resists_operators[resists_operator]  # just an extra precaution
            if 0 <= resists_value <= 300:
                clause = "AND" if clause == "WHERE" or clause == "AND" else "WHERE"
                query += f" {clause} items.{resists_type} {resists_operator} %s"
                params_list.append(resists_value)
            else:
                messages.error(request, f"Invalid resist value, '{resists_value}'.  Must be between 0 and 300.")
                return redirect("/items/search")

        if stat1 != "stat1":  # if the field was not left blank
            clause = "AND" if clause == "WHERE" or clause == "AND" else "WHERE"
            partial_query, error_messages = build_stat_query(clause, stat1, stat1_operator)
            if len(error_messages) == 0:
                query += partial_query
                params_list.append(stat1_value)
            else:
                error_message = "<br />".join(error_messages)
                messages.error(request, error_message)
                return redirect("/items/search")

        if stat2 != "stat2":  # if the field was not left blank
            clause = "AND" if clause == "WHERE" or clause == "AND" else "WHERE"
            partial_query, error_messages = build_stat_query(clause, stat2, stat2_operator)
            if len(error_messages) == 0:
                query += partial_query
                params_list.append(stat2_value)
            else:
                error_message = "<br />".join(error_messages)
                messages.error(request, error_message)
                return redirect("/items/search")

        if container_select != "Container":
            clause = "AND" if clause == "WHERE" or clause == "AND" else "WHERE"
            query += f" {clause} bagtype = %s"
            params_list.append(container_select)
        if container_slots != '0':
            clause = "AND" if clause == "WHERE" or clause == "AND" else "WHERE"
            query += f" {clause} bagslots >= %s"
            params_list.append(container_slots)
        if container_wr != '0':
            clause = "AND" if clause == "WHERE" or clause == "AND" else "WHERE"
            query += f" {clause} bagwr >= %s"
            params_list.append(container_wr)

        if item_has_proc:
            query += " AND (proceffect > 0 and proceffect < 4679)"
        if item_has_click:
            query += " AND (clickeffect > 0 and clickeffect < 4679)"

items/templates/items/base.html
{% extends 'base.html' %}
{% load static %}
{% load data_utilities %}

items/templates/items/best_in_slot.html
{% extends 'items/base.html' %}
{% load static %}
{% load markdown_extras %}
{% block title %}Best in Slot - EQ Archives{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'spells/css/eq-ui.css' %}">
{% endblock %}
{% block content %}
    <div class="container-fluid eq-window-complex-fancy py-4">
        <div class="row row-cols-9">
            {% for index, name in player_classes.items %}
                <div class="col">
                    {# Class 0 doesn't exist, and class 15 (beastlord) and class 16 (berserker) aren't released yet #}
                    {% if index != 0 and index < 15 %}
                        {% if index == class_id %}
                            <a href="/items/bis/{{ index }}"
                               class="btn eq-button-fancy-highlighted eq-button-fancy d-flex flex-column align-items-center rounded-0"
                               style="height: 100px;">
                                <img class="img-fluid" src="/static/images/class_icons/{{ index }}.gif"
                                     alt="{{ name }} icon" style="max-height: 70%; max-width: 70%;">
                                <span class="hidden-print">{{ name }}</span>
                            </a>
                        {% else %}
                            <a href="/items/bis/{{ index }}"
                               class="btn eq-button-fancy d-flex flex-column align-items-center rounded-0"
                               style="height: 100px;">
                                <img class="img-fluid" src="/static/images/class_icons/{{ index }}.gif"
                                     alt="{{ name }} icon" style="max-height: 70%; max-width: 70%;">
                                <span class="hidden-print">{{ name }}</span>
                            </a>
                        {% endif %}
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-12"><h2 class="text-center mb-4">{{ selected_class }} Best in Slot</h2></div>
        {% if class_id == None %}
            <div class="col-2 text-center mt-4 mb-4 align-items-center"><p>Select a class above.</p></div>
        {% else %}
            <div class="col-2">
                <div class="eq-window-fancy flex-column me-3 bis-div" id="bisTab" role="tablist"
                     aria-orientation="vertical">
                    <button class="eq-button-fancy active" id=vanilla-pre-planar-tab" data-bs-toggle="pill"
                            data-bs-target="#vanilla-pre-planar-tab-pane" type="button" role="tab"
                            aria-controls="vanilla-pre-planar-tab-pane" aria-selected="true">Vanilla Pre-Planar Gear
                    </button>
                    <button class="eq-button-fancy" id=vanilla-planar-tab" data-bs-toggle="pill"
                            data-bs-target="#vanilla-planar-tab-pane" type="button" role="tab"
                            aria-controls="vanilla-planar-tab-pane" aria-selected="false">Vanilla Planar Gear
                    </button>
                    <button class="eq-button-fancy" id=kunark-tab" data-bs-toggle="pill"
                            data-bs-target="#kunark-tab-pane" type="button" role="tab"
                            aria-controls="kunark-tab-pane" aria-selected="false">Kunark Gear
                    </button>
                    <button class="eq-button-fancy" id=velious-group-tab" data-bs-toggle="pill"
                            data-bs-target="#velious-group-tab-pane" type="button" role="tab"
                            aria-controls="velious-group-tab-pane" aria-selected="false">Velious Group Gear
                    </button>
                    <button class="eq-button-fancy" id=velious-raid-tab" data-bs-toggle="pill"
                            data-bs-target="#velious-raid-tab-pane" type="button" role="tab"
                            aria-controls="velious-raid-tab-pane" aria-selected="false">Velious Raid Gear
                    </button>
                </div>
            </div>
            <div class="col tab-content" id="bisTabContent">
                <div class="tab-pane fade show active" id="vanilla-pre-planar-tab-pane" role="tabpanel"
                     aria-labelledby="vanilla-pre-planar-tab"
                     tabindex="0">
                    <div class="row px-4">
                        {{ vanilla_pre_planar_file|render_markdown }}
                    </div>
                </div>
                <div class="tab-pane fade" id="vanilla-planar-tab-pane" role="tabpanel"
                     aria-labelledby="vanilla-planar-tab"
                     tabindex="1">
                    <div class="row px-4">
                        {{ vanilla_planar_file|render_markdown }}
                    </div>
                </div>
                <div class="tab-pane fade" id="kunark-tab-pane" role="tabpanel"
                     aria-labelledby="kunark-tab"
                     tabindex="2">
                    <div class="row px-4">
                        {{ kunark_file|render_markdown }}
                    </div>
                </div>
                <div class="tab-pane fade" id="velious-group-tab-pane" role="tabpanel"
                     aria-labelledby="velious-group-tab"
                     tabindex="3">
                    <div class="row px-4">
                        {{ velious_group_file|render_markdown }}
                    </div>
                </div>
                <div class="tab-pane fade" id="velious-raid-tab-pane" role="tabpanel"
                     aria-labelledby="velious-raid-tab"
                     tabindex="4">
                    <div class="row px-4">
                        {{ velious_raid_file|render_markdown }}
                    </div>
                </div>
            </div>
            </div>
        {% endif %}
{% endblock %}

items/templates/items/view_item.html
{% extends 'items/base.html' %}
{% load data_utilities %}
{% load item_filters %}
{% load tradeskill_filters %}
{% load static %}
{% load humanize %}
{% block extra_meta %}
    {% if item.Name %}
        <meta content="EQ Archives" property="og:site_name">
        <meta content="article" property="og:type">
        <meta content="{{ item.get_clean_name }}" property="og:title">
        <meta content="{{ og_description }}" property="og:description">
        <meta name="description" content="EQA Item Information for {{ item.get_clean_name }}">
        <meta content="https://{{ request.get_host }}/static/images/items/item_{{ item.icon }}.png" property="og:image">
        <meta property="og:url" content="https://{{ request.get_host }}/items/view/{{ item.id }}">
        <link rel="canonical" href="https://{{ request.get_host }}/items/view/{{ item.id }}">
    {% endif %}
{% endblock %}
{% block title %} {{ item.get_clean_name }} - EQ Archives{% endblock %}
{% block content %}
    <div class="container py-4">
        <div class="row">
            <h3>{{ item.Name }}</h3>
            <hr/>
            <div class="col">
                <div class="row py-2">
                    <div class="col">
                        {% include 'items/item_stats_template.html' %}
                        <div>
                            <span style="font-size: 10pt"><img
                                    src="{% static "/images/spell_icons/Spellicon_U.png" %}" style="width:18px;"
                                    alt="Lore Icon">&nbsp;<b>Item Lore</b> <span
                                    style="font-size:8pt">(from Identify)</span>: {{ item.lore }}</span>
                        </div>
                    </div>
                    {% if item.idfile != "IT63" and item.idfile != "0" %}
                        <div class="col-12 col-md-4">
                            <model-viewer
                                    alt="3D model of {{ item.Name }}" class="float-end border bg-body-tertiary"
                                    style="min-height: 200px; max-height: 300px;"
                                    src="{{ obj_path }}"
                                    shadow-intensity="1" camera-controls
                                    camera-orbit="45deg 55deg 4m"
                                    touch-action="pan-y"></model-viewer>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="row py-2">
                    <div class="col">
                        {% if drops_from|length > 0 %}
                            <h5>Drops From</h5>
                            <hr/>
                            {% for zone, result_list in drops_from.items %}
                                <div><a style="text-decoration: none;"
                                        href="/zones/view/{{ zone }}">{{ result_list.0.z_long_name }}</a>
                                    <ul>
                                        {% for result in result_list %}
                                            <li><a style="text-decoration: none;"
                                                   href="/npcs/view/{{ result.npc_id }}">{{ result.npc_name|clean_name }}</a>&nbsp;({{ result.modified_drop_chance }}%
                                                x {{ result.lte_multiplier }})
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            {% endfor %}
                        {% else %}
                            <div class="text-disabled">
                                <h5>Drops From</h5>
                                <hr/>
                                <p>This item is not dropped by mobs.</p>
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="row py-2">
                    <div class="col">
                        {% if sold_by|length > 0 %}
                            <h5>Sold By</h5>
                            <hr/>
                            {% for zone, result_list in sold_by.items %}
                                <div><a style="text-decoration: none"
                                        href="/zones/view/{{ zone }}">{{ result_list.0.z_long_name }}</a></div>
                                <ul>
                                    {% for merchant in result_list %}
                                        <li><a style="text-decoration: none"
                                               href="/npcs/view/{{ merchant.npc_id }}">{{ merchant.npc_name|clean_name }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endfor %}
                        {% else %}
                            <div class="text-disabled">
                                <h5>Sold By</h5>
                                <hr/>
                                <p>This item is not found in any merchant lists.</p>
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="row py-2">
                    <div class="col">
                        {% if forage|length > 0 %}
                            <h5>Foraged from:</h5>
                            <hr/>
                            <ul>
                                {% for zone, forage_list in forage.items %}
                                    <li><a style="text-decoration: none;"
                                           href="/zones/view/{{ zone }}">{{ forage_list.0.z_long_name }}</a>&nbsp;({{ forage_list.0.chance }}%)
                                    </li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <div class="text-disabled">
                                <h5>Foraged from:</h5>
                                <hr/>
                                <p>This item is not foraged anywhere.</p>
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="row py-2">
                    <div class="col">
                        {% if ground_spawns|length > 0 %}
                            <h5>Spawns on the ground in:</h5>
                            <hr/>
                            {% for zone, coordinate_list in ground_spawns.items %}
                                <div><a style="text-decoration: none"
                                        href="/zones/view/{{ zone }}">{{ coordinate_list.0.z_long_name }}</a>&nbsp;(y,
                                    x, z)
                                </div>
                                <ul style="list-style: square">
                                    {% for coordinates in coordinate_list %}
                                        <li>
                                            ({{ coordinates.max_y }}, {{ coordinates.max_x }}, {{ coordinates.max_z }})
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endfor %}
                        {% else %}
                            <div class="text-disabled">
                                <h5>Spawns on the Ground:</h5>
                                <hr/>
                                <p>This item does not spawn on the ground.</p>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="row py-2">
                    <div class="col">
                        {% if created_by_these_tradeskill_recipes|length > 0 %}
                            <h5>Player crafted from:</h5>
                            <hr/>
                            {% for tradeskill, recipe_list in created_by_these_tradeskill_recipes.items %}
                                <div>{{ tradeskill|tradeskill_filter }}
                                    <ul>
                                        {% for recipe in recipe_list %}
                                            <li>
                                                <b>Recipe</b>:&nbsp;<a style="text-decoration: none"
                                                                       href="/recipes/view/{{ recipe.recipe_id }}">{{ recipe.recipe_name }}</a>&nbsp;<b>Yield</b>:&nbsp;x{{ recipe.success_count }}
                                                &nbsp;(Trivial: {{ recipe.trivial }})
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            {% endfor %}
                        {% else %}
                            <div class="text-disabled">
                                <h5>Player Crafted from:</h5>
                                <hr/>
                                <p>This item is not crafted by players.</p>
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="row py-2">
                    <div class="col">
                        {% if used_in_these_tradeskill_recipes|length > 0 %}
                            <h5>Used in the following tradeskill recipes:</h5>
                            <hr/>
                            {% for tradeskill, recipe_list in used_in_these_tradeskill_recipes.items %}
                                <div>{{ tradeskill|tradeskill_filter }}
                                    <ul>
                                        {% for recipe in recipe_list %}
                                            <li><a style="text-decoration: none"
                                                   href="/recipes/view/{{ recipe.recipe_id }}">{{ recipe.recipe_name }}</a>
                                                (Trivial: {{ recipe.trivial }})
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            {% endfor %}
                        {% else %}
                            <div class="text-disabled">
                                <h5>Component in the following tradeskill recipes:</h5>
                                <hr/>
                                <p>This item is not a component in any tradeskill recipes.</p>
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="row py-2">
                    <div class="col">
                        {% if related_quests %}
                            <h5>Related Quests</h5>
                            <hr/>
                            <ul>
                                {% for quest in related_quests %}
                                    <li><a href="{% url 'quests:view' quest.id %}">{{ quest }}</a></li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <div class="text-disabled">
                                <h5>Related Quests</h5>
                                <hr/>
                                <p>Information currently unavailable.</p>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block extra_js %}
    <script type="module" src="https://ajax.googleapis.com/ajax/libs/model-viewer/3.4.0/model-viewer.min.js"></script>
{% endblock %}